# Generated by Django 3.2 on 2021-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
