# Generated by Django 3.2 on 2021-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simsell',
            name='sim_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
