# Generated by Django 3.2 on 2021-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_simsell_sim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='company',
            field=models.CharField(choices=[('gp', 'GP'), ('robi', 'ROBI'), ('banglalink', 'BANGLALINK'), ('teletalk', 'TELETALK')], max_length=200),
        ),
    ]
