# Generated by Django 3.2 on 2021-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_sim_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='company',
            field=models.CharField(choices=[('GP', 'GP'), ('ROBI', 'ROBI'), ('BANGLALINK', 'BANGLALINK'), ('TELETALK', 'TELETALK')], max_length=200),
        ),
    ]
