# Generated by Django 3.2 on 2021-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_sim_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCompanyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('paid', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
