# Generated by Django 3.2 on 2021-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_simcompanypayment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcompanypayment',
            name='company',
            field=models.CharField(choices=[('GP', 'GP'), ('ROBI', 'ROBI'), ('BANGLALINK', 'BANGLALINK'), ('TELETALK', 'TELETALK')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='simcompanypayment',
            unique_together={('year', 'month', 'company')},
        ),
    ]
