# Generated by Django 3.2 on 2021-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210502_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsell',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simsell',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
