# Generated by Django 3.2 on 2021-04-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('balance_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6, verbose_name='Account Balance Type')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnx_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6, verbose_name='Transaction Balance Type')),
                ('amount', models.FloatField(default=0)),
                ('tnx_description', models.CharField(max_length=500, verbose_name='Transsaction Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_type',
        ),
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='Account Code'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubAccount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounting.accountcategory'),
            preserve_default=False,
        ),
    ]
