# Generated by Django 3.2 on 2021-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210412_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Account Code'),
        ),
    ]
